"""初始表结构

Revision ID: 0c0466b1db26
Revises: 
Create Date: 2026-06-16 22:32:14.629157+08:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c0466b1db26"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_history', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='预警标题',
               existing_nullable=False)
    op.alter_column('alert_history', 'content',
               existing_type=sa.TEXT(),
               comment='预警内容',
               existing_nullable=True)
    op.alter_column('alert_history', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment='严重程度: low/medium/high/critical',
               existing_nullable=True)
    op.alter_column('alert_history', 'triggered_by',
               existing_type=sa.VARCHAR(length=300),
               comment='触发数据（来源URL）',
               existing_nullable=True)
    op.alter_column('alert_history', 'source_data_id',
               existing_type=sa.UUID(),
               comment='关联原始数据 ID',
               existing_nullable=True)
    op.alter_column('alert_history', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='是否已读',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_history', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               comment='是否已处理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_history', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='触发时间',
               existing_nullable=False)
    op.drop_index('ix_alert_hist_read', table_name='alert_history')
    op.drop_index('ix_alert_hist_rule', table_name='alert_history')
    op.drop_index('ix_alert_hist_trigger', table_name='alert_history')
    op.create_index(op.f('ix_alert_history_is_read'), 'alert_history', ['is_read'], unique=False)
    op.create_index(op.f('ix_alert_history_rule_id'), 'alert_history', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_history_triggered_at'), 'alert_history', ['triggered_at'], unique=False)
    op.alter_column('alert_rules', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='规则名称',
               existing_nullable=False)
    op.alter_column('alert_rules', 'description',
               existing_type=sa.TEXT(),
               comment='规则描述',
               existing_nullable=True)
    op.alter_column('alert_rules', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='监控对象: competitor/product/keyword',
               existing_nullable=True)
    op.alter_column('alert_rules', 'target_id',
               existing_type=sa.UUID(),
               comment='监控对象 ID',
               existing_nullable=True)
    op.alter_column('alert_rules', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='关键词列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('alert_rules', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='监控数据源',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('alert_rules', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment='严重程度: low/medium/high/critical',
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('alert_rules', 'notification_channels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='通知渠道: email/slack/wechat/webhook',
               existing_nullable=True,
               existing_server_default=sa.text('\'["email"]\'::jsonb'))
    op.drop_index('ix_alerts_active', table_name='alert_rules')
    op.create_index(op.f('ix_alert_rules_is_active'), 'alert_rules', ['is_active'], unique=False)
    op.alter_column('analysis_reports', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='报告标题',
               existing_nullable=False)
    op.alter_column('analysis_reports', 'content',
               existing_type=sa.TEXT(),
               comment='报告正文（Markdown）',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.VARCHAR(length=100),
               comment='报告类型: competitor_analysis/swot/trend/alert',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'generated_by',
               existing_type=sa.VARCHAR(length=50),
               comment='生成方式: manual/ai/scheduled',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('analysis_reports', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               comment='AI 模型名称',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'ai_prompt',
               existing_type=sa.TEXT(),
               comment='AI Prompt（用于追溯）',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('analysis_reports', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_reports_intel', table_name='analysis_reports')
    op.drop_index('ix_reports_status', table_name='analysis_reports')
    op.drop_index('ix_reports_type', table_name='analysis_reports')
    op.create_index(op.f('ix_analysis_reports_intelligence_id'), 'analysis_reports', ['intelligence_id'], unique=False)
    op.create_index(op.f('ix_analysis_reports_report_type'), 'analysis_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_analysis_reports_status'), 'analysis_reports', ['status'], unique=False)
    op.alter_column('collected_data', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='标题',
               existing_nullable=True)
    op.alter_column('collected_data', 'content',
               existing_type=sa.TEXT(),
               comment='原始内容',
               existing_nullable=True)
    op.alter_column('collected_data', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='内容 SHA256 哈希（去重）',
               existing_nullable=True)
    op.alter_column('collected_data', 'url',
               existing_type=sa.VARCHAR(length=2000),
               comment='原始链接',
               existing_nullable=True)
    op.alter_column('collected_data', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment='语言',
               existing_nullable=True,
               existing_server_default=sa.text("'zh'::character varying"))
    op.alter_column('collected_data', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='原始结构化数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('collected_data', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='采集时间',
               existing_nullable=False)
    op.alter_column('collected_data', 'processed',
               existing_type=sa.BOOLEAN(),
               comment='是否已处理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_collected_hash', table_name='collected_data')
    op.drop_index('ix_collected_processed', table_name='collected_data')
    op.drop_index('ix_collected_source', table_name='collected_data')
    op.drop_index('ix_collected_time', table_name='collected_data')
    op.drop_index('ix_collected_source_hash', table_name='collected_data')
    op.create_index('ix_collected_source_hash', 'collected_data', ['source_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_collected_data_collected_at'), 'collected_data', ['collected_at'], unique=False)
    op.create_index(op.f('ix_collected_data_content_hash'), 'collected_data', ['content_hash'], unique=False)
    op.create_index(op.f('ix_collected_data_processed'), 'collected_data', ['processed'], unique=False)
    op.create_index(op.f('ix_collected_data_source_id'), 'collected_data', ['source_id'], unique=False)
    op.alter_column('competitor_features', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='功能大类（如 AI/数据分析/协作）',
               existing_nullable=False)
    op.alter_column('competitor_features', 'feature_name',
               existing_type=sa.VARCHAR(length=300),
               comment='功能名称',
               existing_nullable=False)
    op.alter_column('competitor_features', 'support_level',
               existing_type=sa.VARCHAR(length=20),
               comment='支持程度: full / partial / none / unknown',
               existing_nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('competitor_features', 'description',
               existing_type=sa.TEXT(),
               comment='功能详情',
               existing_nullable=True)
    op.alter_column('competitor_features', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='信息来源链接',
               existing_nullable=True)
    op.alter_column('competitor_features', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='核验时间',
               existing_nullable=True)
    op.drop_index('ix_features_category', table_name='competitor_features')
    op.drop_index('ix_features_competitor', table_name='competitor_features')
    op.drop_index('ix_features_competitor_name', table_name='competitor_features')
    op.drop_index('ix_features_name', table_name='competitor_features')
    op.create_index(op.f('ix_competitor_features_category'), 'competitor_features', ['category'], unique=False)
    op.create_index(op.f('ix_competitor_features_competitor_id'), 'competitor_features', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_features_feature_name'), 'competitor_features', ['feature_name'], unique=False)
    op.create_index('ix_feature_competitor_name', 'competitor_features', ['competitor_id', 'feature_name'], unique=False)
    op.alter_column('competitors', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='竞品名称',
               existing_nullable=False)
    op.alter_column('competitors', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               comment='英文名称',
               existing_nullable=True)
    op.alter_column('competitors', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment='官网地址',
               existing_nullable=True)
    op.alter_column('competitors', 'logo_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='Logo 地址',
               existing_nullable=True)
    op.alter_column('competitors', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='竞品层级: direct/indirect/potential',
               existing_server_default=sa.text("'direct'::character varying"))
    op.alter_column('competitors', 'description',
               existing_type=sa.TEXT(),
               comment='竞品描述',
               existing_nullable=True)
    op.alter_column('competitors', 'headquarters',
               existing_type=sa.VARCHAR(length=200),
               comment='总部所在地',
               existing_nullable=True)
    op.alter_column('competitors', 'founded_year',
               existing_type=sa.INTEGER(),
               comment='成立年份',
               existing_nullable=True)
    op.alter_column('competitors', 'employee_count',
               existing_type=sa.VARCHAR(length=50),
               comment='员工规模',
               existing_nullable=True)
    op.alter_column('competitors', 'funding_stage',
               existing_type=sa.VARCHAR(length=100),
               comment='融资阶段',
               existing_nullable=True)
    op.alter_column('competitors', 'total_funding',
               existing_type=sa.VARCHAR(length=100),
               comment='融资总额',
               existing_nullable=True)
    op.alter_column('competitors', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='标签列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('competitors', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='扩展元数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('competitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否活跃',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('competitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_competitors_active', table_name='competitors')
    op.create_index(op.f('ix_competitors_is_active'), 'competitors', ['is_active'], unique=False)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='数据源名称',
               existing_nullable=False)
    op.alter_column('data_sources', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               comment='数据源类型',
               existing_nullable=False)
    op.alter_column('data_sources', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment='数据源 URL',
               existing_nullable=True)
    op.alter_column('data_sources', 'crawl_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='爬虫配置（选择器、频率等）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_sources', 'api_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='API 配置（endpoint, headers, auth）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('data_sources', 'crawl_interval_minutes',
               existing_type=sa.INTEGER(),
               comment='采集间隔（分钟）',
               existing_nullable=True,
               existing_server_default=sa.text('360'))
    op.alter_column('data_sources', 'last_crawled_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='上次采集时间',
               existing_nullable=True)
    op.alter_column('data_sources', 'last_status',
               existing_type=sa.VARCHAR(length=20),
               comment='上次采集状态: success/failed',
               existing_nullable=True)
    op.drop_index('ix_sources_active', table_name='data_sources')
    op.drop_index('ix_sources_type', table_name='data_sources')
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.alter_column('market_intelligence', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='情报标题',
               existing_nullable=False)
    op.alter_column('market_intelligence', 'summary',
               existing_type=sa.TEXT(),
               comment='情报摘要',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='分类: product_update/funding/partnership/hr/policy',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment='情感: positive/neutral/negative',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'importance',
               existing_type=sa.INTEGER(),
               comment='重要度 1-5',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('market_intelligence', 'source_url',
               existing_type=sa.VARCHAR(length=2000),
               comment='来源链接',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'source_name',
               existing_type=sa.VARCHAR(length=300),
               comment='来源名称',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='情报发布日期',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('market_intelligence', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_intel_category', table_name='market_intelligence')
    op.drop_index('ix_intel_competitor', table_name='market_intelligence')
    op.drop_index('ix_intel_published', table_name='market_intelligence')
    op.drop_index('ix_intel_sentiment', table_name='market_intelligence')
    op.create_index(op.f('ix_market_intelligence_category'), 'market_intelligence', ['category'], unique=False)
    op.create_index(op.f('ix_market_intelligence_competitor_id'), 'market_intelligence', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_market_intelligence_published_at'), 'market_intelligence', ['published_at'], unique=False)
    op.create_index(op.f('ix_market_intelligence_sentiment'), 'market_intelligence', ['sentiment'], unique=False)
    op.alter_column('pricing_history', 'plan_name',
               existing_type=sa.VARCHAR(length=200),
               comment='套餐名称',
               existing_nullable=False)
    op.alter_column('pricing_history', 'old_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='旧价格',
               existing_nullable=True)
    op.alter_column('pricing_history', 'new_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='新价格',
               existing_nullable=False)
    op.alter_column('pricing_history', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment='币种',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))
    op.alter_column('pricing_history', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               comment='计费周期: monthly/yearly',
               existing_nullable=True)
    op.alter_column('pricing_history', 'change_type',
               existing_type=sa.VARCHAR(length=20),
               comment='变动类型: increase/decrease/new_plan/removed',
               existing_nullable=True)
    op.alter_column('pricing_history', 'change_description',
               existing_type=sa.TEXT(),
               comment='变动说明',
               existing_nullable=True)
    op.alter_column('pricing_history', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='信息来源',
               existing_nullable=True)
    op.alter_column('pricing_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='检测时间',
               existing_nullable=False)
    op.drop_index('ix_pricing_competitor', table_name='pricing_history')
    op.drop_index('ix_pricing_detected', table_name='pricing_history')
    op.create_index(op.f('ix_pricing_history_competitor_id'), 'pricing_history', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_pricing_history_detected_at'), 'pricing_history', ['detected_at'], unique=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='产品名称',
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='产品分类',
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment='产品描述',
               existing_nullable=True)
    op.alter_column('products', 'launch_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='上线时间',
               existing_nullable=True)
    op.alter_column('products', 'pricing_model',
               existing_type=sa.VARCHAR(length=200),
               comment='定价模式（免费/订阅/一次性）',
               existing_nullable=True)
    op.alter_column('products', 'target_market',
               existing_type=sa.VARCHAR(length=300),
               comment='目标市场',
               existing_nullable=True)
    op.alter_column('products', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment='产品页面',
               existing_nullable=True)
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='标签',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_products_competitor', table_name='products')
    op.create_index(op.f('ix_products_competitor_id'), 'products', ['competitor_id'], unique=False)
    op.alter_column('sentiment_data', 'platform',
               existing_type=sa.VARCHAR(length=100),
               comment='平台: twitter/weibo/reddit/app_store',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'content',
               existing_type=sa.TEXT(),
               comment='原始内容',
               existing_nullable=False)
    op.alter_column('sentiment_data', 'author',
               existing_type=sa.VARCHAR(length=200),
               comment='作者',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment='情感: positive/neutral/negative',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='情感分数 0-1',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'engagement_count',
               existing_type=sa.INTEGER(),
               comment='互动量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sentiment_data', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='发布时间',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'source_url',
               existing_type=sa.VARCHAR(length=2000),
               comment='来源链接',
               existing_nullable=True)
    op.drop_index('ix_sentiment_competitor', table_name='sentiment_data')
    op.drop_index('ix_sentiment_platform', table_name='sentiment_data')
    op.drop_index('ix_sentiment_published', table_name='sentiment_data')
    op.drop_index('ix_sentiment_type', table_name='sentiment_data')
    op.create_index(op.f('ix_sentiment_data_competitor_id'), 'sentiment_data', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_sentiment_data_platform'), 'sentiment_data', ['platform'], unique=False)
    op.create_index(op.f('ix_sentiment_data_published_at'), 'sentiment_data', ['published_at'], unique=False)
    op.create_index(op.f('ix_sentiment_data_sentiment'), 'sentiment_data', ['sentiment'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='admin/analyst/viewer',
               existing_nullable=True,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='admin/analyst/viewer',
               existing_nullable=True,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.drop_index(op.f('ix_sentiment_data_sentiment'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_published_at'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_platform'), table_name='sentiment_data')
    op.drop_index(op.f('ix_sentiment_data_competitor_id'), table_name='sentiment_data')
    op.create_index('ix_sentiment_type', 'sentiment_data', ['sentiment'], unique=False)
    op.create_index('ix_sentiment_published', 'sentiment_data', ['published_at'], unique=False)
    op.create_index('ix_sentiment_platform', 'sentiment_data', ['platform'], unique=False)
    op.create_index('ix_sentiment_competitor', 'sentiment_data', ['competitor_id'], unique=False)
    op.alter_column('sentiment_data', 'source_url',
               existing_type=sa.VARCHAR(length=2000),
               comment=None,
               existing_comment='来源链接',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='发布时间',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'engagement_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='互动量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sentiment_data', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='情感分数 0-1',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='情感: positive/neutral/negative',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'author',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
    op.alter_column('sentiment_data', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='原始内容',
               existing_nullable=False)
    op.alter_column('sentiment_data', 'platform',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='平台: twitter/weibo/reddit/app_store',
               existing_nullable=True)
    op.drop_index(op.f('ix_products_competitor_id'), table_name='products')
    op.create_index('ix_products_competitor', 'products', ['competitor_id'], unique=False)
    op.alter_column('products', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('products', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='标签',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='产品页面',
               existing_nullable=True)
    op.alter_column('products', 'target_market',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='目标市场',
               existing_nullable=True)
    op.alter_column('products', 'pricing_model',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='定价模式（免费/订阅/一次性）',
               existing_nullable=True)
    op.alter_column('products', 'launch_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上线时间',
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='产品描述',
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='产品分类',
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='产品名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_pricing_history_detected_at'), table_name='pricing_history')
    op.drop_index(op.f('ix_pricing_history_competitor_id'), table_name='pricing_history')
    op.create_index('ix_pricing_detected', 'pricing_history', ['detected_at'], unique=False)
    op.create_index('ix_pricing_competitor', 'pricing_history', ['competitor_id'], unique=False)
    op.alter_column('pricing_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='检测时间',
               existing_nullable=False)
    op.alter_column('pricing_history', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='信息来源',
               existing_nullable=True)
    op.alter_column('pricing_history', 'change_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='变动说明',
               existing_nullable=True)
    op.alter_column('pricing_history', 'change_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='变动类型: increase/decrease/new_plan/removed',
               existing_nullable=True)
    op.alter_column('pricing_history', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='计费周期: monthly/yearly',
               existing_nullable=True)
    op.alter_column('pricing_history', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='币种',
               existing_nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))
    op.alter_column('pricing_history', 'new_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='新价格',
               existing_nullable=False)
    op.alter_column('pricing_history', 'old_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='旧价格',
               existing_nullable=True)
    op.alter_column('pricing_history', 'plan_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='套餐名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_market_intelligence_sentiment'), table_name='market_intelligence')
    op.drop_index(op.f('ix_market_intelligence_published_at'), table_name='market_intelligence')
    op.drop_index(op.f('ix_market_intelligence_competitor_id'), table_name='market_intelligence')
    op.drop_index(op.f('ix_market_intelligence_category'), table_name='market_intelligence')
    op.create_index('ix_intel_sentiment', 'market_intelligence', ['sentiment'], unique=False)
    op.create_index('ix_intel_published', 'market_intelligence', ['published_at'], unique=False)
    op.create_index('ix_intel_competitor', 'market_intelligence', ['competitor_id'], unique=False)
    op.create_index('ix_intel_category', 'market_intelligence', ['category'], unique=False)
    op.alter_column('market_intelligence', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('market_intelligence', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('market_intelligence', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='情报发布日期',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'source_name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='来源名称',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'source_url',
               existing_type=sa.VARCHAR(length=2000),
               comment=None,
               existing_comment='来源链接',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'importance',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='重要度 1-5',
               existing_nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('market_intelligence', 'sentiment',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='情感: positive/neutral/negative',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='分类: product_update/funding/partnership/hr/policy',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='情报摘要',
               existing_nullable=True)
    op.alter_column('market_intelligence', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='情报标题',
               existing_nullable=False)
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.create_index('ix_sources_type', 'data_sources', ['source_type'], unique=False)
    op.create_index('ix_sources_active', 'data_sources', ['is_active'], unique=False)
    op.alter_column('data_sources', 'last_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='上次采集状态: success/failed',
               existing_nullable=True)
    op.alter_column('data_sources', 'last_crawled_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='上次采集时间',
               existing_nullable=True)
    op.alter_column('data_sources', 'crawl_interval_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='采集间隔（分钟）',
               existing_nullable=True,
               existing_server_default=sa.text('360'))
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('data_sources', 'api_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='API 配置（endpoint, headers, auth）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_sources', 'crawl_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='爬虫配置（选择器、频率等）',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('data_sources', 'url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='数据源 URL',
               existing_nullable=True)
    op.alter_column('data_sources', 'source_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='数据源类型',
               existing_nullable=False)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='数据源名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_competitors_is_active'), table_name='competitors')
    op.create_index('ix_competitors_active', 'competitors', ['is_active'], unique=False)
    op.alter_column('competitors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitors', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否活跃',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('competitors', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展元数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('competitors', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='标签列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('competitors', 'total_funding',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='融资总额',
               existing_nullable=True)
    op.alter_column('competitors', 'funding_stage',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='融资阶段',
               existing_nullable=True)
    op.alter_column('competitors', 'employee_count',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='员工规模',
               existing_nullable=True)
    op.alter_column('competitors', 'founded_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成立年份',
               existing_nullable=True)
    op.alter_column('competitors', 'headquarters',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='总部所在地',
               existing_nullable=True)
    op.alter_column('competitors', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='竞品描述',
               existing_nullable=True)
    op.alter_column('competitors', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment=None,
               existing_comment='竞品层级: direct/indirect/potential',
               existing_server_default=sa.text("'direct'::character varying"))
    op.alter_column('competitors', 'logo_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='Logo 地址',
               existing_nullable=True)
    op.alter_column('competitors', 'website',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='官网地址',
               existing_nullable=True)
    op.alter_column('competitors', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='英文名称',
               existing_nullable=True)
    op.alter_column('competitors', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='竞品名称',
               existing_nullable=False)
    op.drop_index('ix_feature_competitor_name', table_name='competitor_features')
    op.drop_index(op.f('ix_competitor_features_feature_name'), table_name='competitor_features')
    op.drop_index(op.f('ix_competitor_features_competitor_id'), table_name='competitor_features')
    op.drop_index(op.f('ix_competitor_features_category'), table_name='competitor_features')
    op.create_index('ix_features_name', 'competitor_features', ['feature_name'], unique=False)
    op.create_index('ix_features_competitor_name', 'competitor_features', ['competitor_id', 'feature_name'], unique=True)
    op.create_index('ix_features_competitor', 'competitor_features', ['competitor_id'], unique=False)
    op.create_index('ix_features_category', 'competitor_features', ['category'], unique=False)
    op.alter_column('competitor_features', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='核验时间',
               existing_nullable=True)
    op.alter_column('competitor_features', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='信息来源链接',
               existing_nullable=True)
    op.alter_column('competitor_features', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='功能详情',
               existing_nullable=True)
    op.alter_column('competitor_features', 'support_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='支持程度: full / partial / none / unknown',
               existing_nullable=True,
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('competitor_features', 'feature_name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='功能名称',
               existing_nullable=False)
    op.alter_column('competitor_features', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='功能大类（如 AI/数据分析/协作）',
               existing_nullable=False)
    op.drop_index(op.f('ix_collected_data_source_id'), table_name='collected_data')
    op.drop_index(op.f('ix_collected_data_processed'), table_name='collected_data')
    op.drop_index(op.f('ix_collected_data_content_hash'), table_name='collected_data')
    op.drop_index(op.f('ix_collected_data_collected_at'), table_name='collected_data')
    op.drop_index('ix_collected_source_hash', table_name='collected_data')
    op.create_index('ix_collected_source_hash', 'collected_data', ['source_id', 'content_hash'], unique=True)
    op.create_index('ix_collected_time', 'collected_data', ['collected_at'], unique=False)
    op.create_index('ix_collected_source', 'collected_data', ['source_id'], unique=False)
    op.create_index('ix_collected_processed', 'collected_data', ['processed'], unique=False)
    op.create_index('ix_collected_hash', 'collected_data', ['content_hash'], unique=False)
    op.alter_column('collected_data', 'processed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已处理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('collected_data', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='采集时间',
               existing_nullable=False)
    op.alter_column('collected_data', 'raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='原始结构化数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('collected_data', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='语言',
               existing_nullable=True,
               existing_server_default=sa.text("'zh'::character varying"))
    op.alter_column('collected_data', 'url',
               existing_type=sa.VARCHAR(length=2000),
               comment=None,
               existing_comment='原始链接',
               existing_nullable=True)
    op.alter_column('collected_data', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='内容 SHA256 哈希（去重）',
               existing_nullable=True)
    op.alter_column('collected_data', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='原始内容',
               existing_nullable=True)
    op.alter_column('collected_data', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='标题',
               existing_nullable=True)
    op.drop_index(op.f('ix_analysis_reports_status'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_report_type'), table_name='analysis_reports')
    op.drop_index(op.f('ix_analysis_reports_intelligence_id'), table_name='analysis_reports')
    op.create_index('ix_reports_type', 'analysis_reports', ['report_type'], unique=False)
    op.create_index('ix_reports_status', 'analysis_reports', ['status'], unique=False)
    op.create_index('ix_reports_intel', 'analysis_reports', ['intelligence_id'], unique=False)
    op.alter_column('analysis_reports', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('analysis_reports', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('analysis_reports', 'ai_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AI Prompt（用于追溯）',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='AI 模型名称',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'generated_by',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='生成方式: manual/ai/scheduled',
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('analysis_reports', 'report_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='报告类型: competitor_analysis/swot/trend/alert',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态',
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('analysis_reports', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='报告正文（Markdown）',
               existing_nullable=True)
    op.alter_column('analysis_reports', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='报告标题',
               existing_nullable=False)
    op.drop_index(op.f('ix_alert_rules_is_active'), table_name='alert_rules')
    op.create_index('ix_alerts_active', 'alert_rules', ['is_active'], unique=False)
    op.alter_column('alert_rules', 'notification_channels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='通知渠道: email/slack/wechat/webhook',
               existing_nullable=True,
               existing_server_default=sa.text('\'["email"]\'::jsonb'))
    op.alter_column('alert_rules', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='严重程度: low/medium/high/critical',
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('alert_rules', 'sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='监控数据源',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('alert_rules', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='关键词列表',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('alert_rules', 'target_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='监控对象 ID',
               existing_nullable=True)
    op.alter_column('alert_rules', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='监控对象: competitor/product/keyword',
               existing_nullable=True)
    op.alter_column('alert_rules', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='规则描述',
               existing_nullable=True)
    op.alter_column('alert_rules', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='规则名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_alert_history_triggered_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_rule_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_is_read'), table_name='alert_history')
    op.create_index('ix_alert_hist_trigger', 'alert_history', ['triggered_at'], unique=False)
    op.create_index('ix_alert_hist_rule', 'alert_history', ['rule_id'], unique=False)
    op.create_index('ix_alert_hist_read', 'alert_history', ['is_read'], unique=False)
    op.alter_column('alert_history', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='触发时间',
               existing_nullable=False)
    op.alter_column('alert_history', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已处理',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_history', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已读',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_history', 'source_data_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联原始数据 ID',
               existing_nullable=True)
    op.alter_column('alert_history', 'triggered_by',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='触发数据（来源URL）',
               existing_nullable=True)
    op.alter_column('alert_history', 'severity',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='严重程度: low/medium/high/critical',
               existing_nullable=True)
    op.alter_column('alert_history', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='预警内容',
               existing_nullable=True)
    op.alter_column('alert_history', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='预警标题',
               existing_nullable=False)
    # ### end Alembic commands ###